---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: containers.dev.maio.me/library/rust
    tag: latest

params:
  BUILD_ARGS: "--release"

inputs:
- name: source

outputs:
  name: output

run:
  path: source/ci/tasks/rust/build.sh