[package]
authors = ["Sean Johnson <sean@maio.me>"]
edition = "2018"
name = "miscutils-ssl-tester"
version = "0.1.0"

[dependencies]
failure = "0.1.7"
openssl = "0.10"
openssl-sys = "0.9"
structopt = "0.3.14"

[dependencies.miscutils-core]
path = "../core"
