---

resources:
- name: source
  type: git
  icon: git
  source:
    .: (( inject meta.repository.source ))

# - name: commons
#   type: git
#   icon: git
#   source:
#     .: (( inject meta.upstream.commons ))

jobs:
- name: "cargo test"
  public: true
  plan:
  - get: source
    trigger: true
  - task: "run tests"
    file: (( grab meta.tasks.cargo-test ))

- name: "build miscutils"
  public: true
  plan:
  - get: source
    trigger: true
    passed:
    - "cargo test"
  - task: "cargo build"
    file: (( grab meta.tasks.cargo-build ))