meta:
  target:   glow
  url:      https://concourse.dev.maio.me
  team:     main

  name:     miscutils
  pipeline: miscutils

  repository:
    source:
      uri: https://glow.dev.maio.me/seanj/miscutils.git
      branch: master

  tasks:
    cargo-build: source/ci/tasks/rust/build.yml
    cargo-check: source/ci/tasks/rust/check.yml
    cargo-test: source/ci/tasks/rust/test.yml
    img-build-oci: commons/tasks/img/build-oci.yml
    img-write-tags: commons/tasks/img/write-tags.yml

  upstream:
    commons:
      uri: "https://glow.dev.maio.me/containers/commons.git"
      branch: "master"